# Generated by Django 4.0.4 on 2022-11-03 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_laporankegiatan_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengurus',
            name='pik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.pikr'),
        ),
    ]
