# Generated by Django 4.0.4 on 2022-11-03 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_pengurus_pik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('pik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pikr')),
            ],
        ),
    ]
