# Generated by Django 4.0.4 on 2022-11-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_anggota'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporankegiatan',
            name='deskripsi',
            field=models.TextField(null=True),
        ),
    ]
