# Generated by Django 4.0.4 on 2022-11-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_laporankegiatan_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pikr',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
