# Generated by Django 4.0.4 on 2022-11-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_pikr_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporankegiatan',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='laporankegiatan',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
