# Generated by Django 4.0.4 on 2022-11-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_laporankegiatan_created_laporankegiatan_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laporankegiatan',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='anggota',
            name='jenisKelamin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
