# Generated by Django 4.0.4 on 2022-11-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_laporankegiatan_options_anggota_jeniskelamin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='jenisKelamin',
            field=models.CharField(choices=[('1', 'Laki-laki'), ('2', 'Perempuan')], default='1', max_length=1),
        ),
    ]
