# Generated by Django 4.0.4 on 2022-11-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_anggota_jeniskelamin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pikr',
            name='fileK0',
            field=models.FileField(blank=True, null=True, upload_to='k0/'),
        ),
    ]
