# Generated by Django 4.0.4 on 2022-11-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_pikr_filek0'),
    ]

    operations = [
        migrations.AddField(
            model_name='pikr',
            name='deskripsi',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
