# Generated by Django 4.0.4 on 2022-11-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_pikr_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='jabatan',
            field=models.CharField(default='Anggota', max_length=50),
        ),
    ]
